apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
stringData:
  root-user: {{ .Values.mongodb.auth.rootUser | quote }}
  root-password: {{ .Values.mongodb.auth.rootPassword | quote }}
