{{- if not (hasKey .Values.environments .Values.targetEnv) }}
{{- fail (printf "Invalid targetEnv: %s" .Values.targetEnv) }}
{{- end }}

{{- $env := index .Values.environments .Values.targetEnv }}
{{- range $svc := $env.services }}
{{- range $secret := $svc.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $svc.name }}-{{ $secret.name }}
  namespace: {{ $env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $svc.name }}-store
    kind: SecretStore
  target:
    name: {{ $svc.name }}-{{ $secret.name }}
  data:
  {{- range $key := $secret.keys }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $secret.path }}
      property: {{ $key }}
  {{- end }}
---
{{- end }}
{{- end }}