{{- if not (hasKey .Values.environments .Values.targetEnv) }}
{{- fail (printf "Invalid targetEnv: %s" .Values.targetEnv) }}
{{- end }}

{{- $env := index .Values.environments .Values.targetEnv }}
{{- range $env.services }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .name }}-store
  namespace: {{ $env.namespace }}
spec:
  provider:
    vault:
      server: {{ $.Values.vault.server }}
      path: {{ $.Values.vault.kvPath }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ $.Values.vault.mountPath }}
          role: {{ .name }}-{{ $.Values.targetEnv }}-role
          serviceAccountRef:
            name: {{ .name }}
---
{{- end }}