{{- if not (hasKey .Values.environments .Values.targetEnv) }}
{{- fail (printf "Invalid targetEnv: %s" .Values.targetEnv) }}
{{- end }}

{{- $env := index .Values.environments .Values.targetEnv }}
{{- range $env.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $env.namespace }}
---
{{- end }}