#ENC[AES256_GCM,data:1Y07UDRKxxmt3MxxP5RF4ZjaGwtS/gA/XBi6dnnGivt1zroZMieO0f5EKQM=,iv:8K9kXBVOqK/VMuLs72cpaCSB1pAANqRmSX6dQybYKMg=,tag:JmfhBQm5U9DXBtIuHOS3QA==,type:comment]
#ENC[AES256_GCM,data:tftklJfVZ9C7mNkM6vyc7sfRFgfSPu7Zo67hnOfPGuimWORh,iv:TT4QQw9Yr02YR0b0jvQKmsKIOKJOBv4F2uc+D3stmuQ=,tag:+vpY0njFAHHbIDiCblskjg==,type:comment]
mongodb:
    auth:
        rootUser: ENC[AES256_GCM,data:5S/8QQ==,iv:mnM5jdo7dXJYJbX40nHTXpG8ozWK8yEbUvCmPF59J30=,tag:IMRg1Tp9xYRtcjA3Tp2W5Q==,type:str]
        rootPassword: ENC[AES256_GCM,data:7fWEEYh2N4hj0E0=,iv:3ehuCQh9Ms2qaNBoU/lG/3MOrt2jMdNaJf+Icrquz5M=,tag:f5Q6VtenBSs72yUqFNZBeg==,type:str]
sops:
    age:
        - recipient: age13zz9xmh0gxzwyed06wg2qgwrc0vhsyp3g3w03l88n0nldk93v3gq8u6csq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WGtMdTJDd0k4UCtqOUtQ
            MlErU2ExRWQ4RUorTXZqNjJtaTB4U2xpN0RFClFxZXdFQVZkV01CaGl6eG5KbldU
            WGFKTkxaWldhYS9WR0QwUXBwaU8rTmcKLS0tIDVwRUkwSVF1Q0h3eCs3eG9ZTTVa
            NHZDQ3crQm5FOVVxaHNza3lycmlWVWcK4EoLvVoASVNWfvgl4vAAz6K25yczX7WM
            5Y2faCMy2hgNkQu1P/sRDkYEzKjjJRl18fNobZir45vRdet145KxOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T23:21:09Z"
    mac: ENC[AES256_GCM,data:iAuewuwk/P404aE6tWDbumPRdREkbrvpllBS3WK6DlbmetbQICnyUvYmx5bVyZTAsz88NFFgVhCo2ovcjZp+U0Oz0s0WEzmHfIAFd2Mqqa2egRUxT+y0fc61we4RLstVKzGFa6P9DcOjaORD09jAfkduFGeIMLR0lXBlIEjjuX0=,iv:c/igxiwWJbCkj7yOCj6+O0BAfECD3BoShPofAu1ucy8=,tag:/keONYiZtrVDHyt6CzMD+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
